groups/urls.py
from django.urls import path, include
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug>', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>', views.LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>', views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<pk>', views.DeletePost.as_view(), name='delete'),
]

starsocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks')
]

groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from . import models

# Create your views here.

from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model= Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Warning already a member')
        else:
            messages.success(self.request,'You are now a member')
        
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(user=self.request.user, group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')

        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-4">
    <h1>{{group.name}}</h1>
    <h6>Member Count: {{group.members.count}}

    <span class="float-right">
        {% if user in group.members.all %}
            <a class="btn btn-warning" href="{% url 'groups:leave' slug=group.slug %}">Leave</a>
        {% else %}
            <a class="btn btn-info" href="{% url 'groups:join' slug=group.slug %}">Join</a>
        {% endif %}
    </span>
    </h6>
</div>
{% endblock %}

{% block group_content %}

<div class="col-8">
    {% if group.post.count == 0 %}
        <h2>No Posts in this group</h2>
    {% else %}

        {% for post in group.post.all %}
            {% include "posts/_posts.html" %}
        {% endfor %}

    {% endif %}
</div>


{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}

    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary">

    </form>

{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-4">
    {% if user.is_authenticated %}

    <h2>Welcome</h2>
    <a href="{% url 'posts:for_user' username=user.username %}">
        @{{user.username}}
    </a>
    {% endif %}

    <h2>Groups</h2>
    <p>Welcome to the groups page!</p>


{% if user.is_authenticated %}

<a href="{% url 'groups:create' %}" class="btn btn-success">
    Create Group
</a>
{% endif %}
</div>
{% endblock %}

{% block group_content %}
    <div class="col-8">
        <br>
            {% for group in object_list %}
            <div class="card card-shadow">
                <a class="card-header" href="{% url 'groups:single' slug=group.slug %}">
                    <h3>{{group.name}}</h3>
                </a>
                    <div class="container">
                        {{group.description_html|safe}}
                        <div class="row">
                            <div class="col-4">
                                <span class="badge badge-secondary">{{group.members.count}}</span>
                                members
                            </div>
                            <div class="col-4"><span class="badge badge-info">{{group.posts.count}}</span>
                                posts
                            </div>
                        </div>
                    </div>
                    <br>
                </div>
                <br>
            {% endfor %}
    </div>
{% endblock %}