posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>', views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<pk>', views.DeletePost.as_view(), name='delete'),
]

starsocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks')
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='post', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username, 'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from django.contrib import messages

from . import models
from . import forms

from django.contrib.auth import get_user_model

# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    models = models.Post
    select_related = ('user', 'group')

class UserPost(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args,**kwargs)

posts/templates/posts/_posts.html
<div class="container">
    <h3>{{post.message_html|safe}}</h3>
        <span>
            <a href="{% url 'posts:for_user' username=post.user.username %}">
                <strong>@{{post.user.username}}</strong>
            </a>
            
            <time>
                <a class="text-muted" href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.created_at}}</a>
            </time>
            
            {% if user.is_authenticated and post.user == user and not hide_delete %}
                <a title="delete" href="{% url 'posts:delete' pk=post.pk %}" class="btn btn-outline-danger btn-sm">Delete</a>
            {% endif %}
        </span>  
</div>

<hr>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="post-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

<h3>Are you sure you want to delete this post?</h3>

<div class="container">
    {% include 'posts/_posts.html' with post=object hide_delete=True %}
</div>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-warning">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-8">
    {% include "posts/_posts.html" %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
<h3>Create New Post</h3>

<form class="container" action="" method='POST' action="{% url 'posts:create' %}">
    {% csrf_token %}

    {% bootstrap_form form %}

    <input type="submit" value="Post" class="btn btn-primary">

</form>



{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
    <div class="col-4">
        {% if user.is_authenticated %}
        <div class="card card-with-shadow">
            <h5>Your Groups</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                    <li>
                        <a href="{% url 'groups:single' slug=member_group.group.slug %}">Group</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <div class="card card-with-shadow">
            <h5>All Groups</h5>
            <ul>
                {% for other_group in get_other_groups %}
                    <li>
                        <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}


{% block post_content %}
    <div class="col-8">
        {% for post in post_list %}
            {% include "posts/_posts.html" %}
        {% endfor %}
    </div>
{% endblock %}

{% block post_content %}{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-4">
    <h1>{{post_user.username}}</h1>
</div>
{% endblock %}

{% block post_content %}
    <div class="col-8">
        {% for post in post_list %}
            {% include "posts/_posts.html" %}
        {% endfor %}
    </div>
{% endblock %}